version: '3.7'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    deploy:
      replicas: 3
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.3.0
    deploy:
      replicas: 3
    ports:
      - "9092"
    environment:
      #KAFKA_ADVERTISED_HOST_NAME: "${DOCKER_MACHINE_VM_IP}"
      #KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
